---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ory-kratos-admin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ory-kratos-admin
  template:
    metadata:
      labels:
        app: ory-kratos-admin
    spec:
      containers:
      - name: ory-kratos-admin
        image: ory-kratos-admin
        command:
        - sh
        - -c
        - ./bin/ory_kratos_admin eval OryKratosAdmin.Release.migrate && ./bin/ory_kratos_admin start

        resources:
          limits:
            memory: 256Mi
            cpu: 500m
          requests:
            memory: 64Mi
            cpu: 50m

        ports:
        - name: http
          containerPort: 4000

        env:
        - name: PHX_SERVER
          value: 'true'

        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: ory-kratos-pg
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: ory-kratos-pg

        envFrom:
        - configMapRef:
            name: ory-kratos-admin
        - secretRef:
            name: ory-kratos-admin
